apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootcamp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bootcamp-app
  template:
    metadata:
      labels:
        app: bootcamp-app
    spec:
      containers:
        - name: bootcamp-app
          image: your-dockerhub/bootcamp-app:1.0.0
          ports:
            - containerPort: 5000
          env:
            - name: WELCOME_MSG
              valueFrom:
                configMapKeyRef:
                  name: bootcamp-config
                  key: WELCOME_MSG
